spring.application.name=backend

# Conexao com o Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/arredadb
spring.datasource.username=arreda_user
spring.datasource.password=ifmg_arreda_app
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=token-super-seguro-arreda-app